# Generated by Django 4.1.4 on 2023-01-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_date',
            field=models.DateField(default='2023-01-18'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='review_date',
            field=models.DateField(default='2023-01-18'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='review_date',
            field=models.DateField(default='2023-01-18'),
        ),
        migrations.AlterField(
            model_name='seriesreview',
            name='review_date',
            field=models.DateField(default='2023-01-18'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug_category',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
